/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-21 at 21:34:00 UTC 
 * Modify at your own risk.
 */

package com.appspot.shagai1111.users;

/**
 * Service definition for Users (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UsersRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Users extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the users library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://shagai1111.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "users/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Users(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Users(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the User collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Users users = new Users(...);}
   *   {@code Users.User.List request = users.user().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public User user() {
    return new User();
  }

  /**
   * The "user" collection of methods.
   */
  public class User {

    /**
     * Create a request for the method "user.get".
     *
     * This request holds the parameters needed by the the users server.  After setting any optional
     * parameters, call the {@link Get#execute()} method to invoke the remote operation.
     *
     * @param id
     * @return the request
     */
    public Get get(java.lang.Long id) throws java.io.IOException {
      Get result = new Get(id);
      initialize(result);
      return result;
    }

    public class Get extends UsersRequest<com.appspot.shagai1111.users.model.User> {

      private static final String REST_PATH = "users/{id}";

      /**
       * Create a request for the method "user.get".
       *
       * This request holds the parameters needed by the the users server.  After setting any optional
       * parameters, call the {@link Get#execute()} method to invoke the remote operation. <p> {@link
       * Get#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected Get(java.lang.Long id) {
        super(Users.this, "GET", REST_PATH, null, com.appspot.shagai1111.users.model.User.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Get setAlt(java.lang.String alt) {
        return (Get) super.setAlt(alt);
      }

      @Override
      public Get setFields(java.lang.String fields) {
        return (Get) super.setFields(fields);
      }

      @Override
      public Get setKey(java.lang.String key) {
        return (Get) super.setKey(key);
      }

      @Override
      public Get setOauthToken(java.lang.String oauthToken) {
        return (Get) super.setOauthToken(oauthToken);
      }

      @Override
      public Get setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Get) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Get setQuotaUser(java.lang.String quotaUser) {
        return (Get) super.setQuotaUser(quotaUser);
      }

      @Override
      public Get setUserIp(java.lang.String userIp) {
        return (Get) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public Get setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public Get set(String parameterName, Object value) {
        return (Get) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "user.getAll".
     *
     * This request holds the parameters needed by the the users server.  After setting any optional
     * parameters, call the {@link GetAll#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public GetAll getAll() throws java.io.IOException {
      GetAll result = new GetAll();
      initialize(result);
      return result;
    }

    public class GetAll extends UsersRequest<com.appspot.shagai1111.users.model.UserCollection> {

      private static final String REST_PATH = "usercollection";

      /**
       * Create a request for the method "user.getAll".
       *
       * This request holds the parameters needed by the the users server.  After setting any optional
       * parameters, call the {@link GetAll#execute()} method to invoke the remote operation. <p> {@link
       * GetAll#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected GetAll() {
        super(Users.this, "GET", REST_PATH, null, com.appspot.shagai1111.users.model.UserCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetAll setAlt(java.lang.String alt) {
        return (GetAll) super.setAlt(alt);
      }

      @Override
      public GetAll setFields(java.lang.String fields) {
        return (GetAll) super.setFields(fields);
      }

      @Override
      public GetAll setKey(java.lang.String key) {
        return (GetAll) super.setKey(key);
      }

      @Override
      public GetAll setOauthToken(java.lang.String oauthToken) {
        return (GetAll) super.setOauthToken(oauthToken);
      }

      @Override
      public GetAll setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetAll) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetAll setQuotaUser(java.lang.String quotaUser) {
        return (GetAll) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetAll setUserIp(java.lang.String userIp) {
        return (GetAll) super.setUserIp(userIp);
      }

      @Override
      public GetAll set(String parameterName, Object value) {
        return (GetAll) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "create".
   *
   * This request holds the parameters needed by the the users server.  After setting any optional
   * parameters, call the {@link Create#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.shagai1111.users.model.User}
   * @return the request
   */
  public Create create(com.appspot.shagai1111.users.model.User content) throws java.io.IOException {
    Create result = new Create(content);
    initialize(result);
    return result;
  }

  public class Create extends UsersRequest<com.appspot.shagai1111.users.model.User> {

    private static final String REST_PATH = "createUser";

    /**
     * Create a request for the method "create".
     *
     * This request holds the parameters needed by the the users server.  After setting any optional
     * parameters, call the {@link Create#execute()} method to invoke the remote operation. <p> {@link
     * Create#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.shagai1111.users.model.User}
     * @since 1.13
     */
    protected Create(com.appspot.shagai1111.users.model.User content) {
      super(Users.this, "POST", REST_PATH, content, com.appspot.shagai1111.users.model.User.class);
    }

    @Override
    public Create setAlt(java.lang.String alt) {
      return (Create) super.setAlt(alt);
    }

    @Override
    public Create setFields(java.lang.String fields) {
      return (Create) super.setFields(fields);
    }

    @Override
    public Create setKey(java.lang.String key) {
      return (Create) super.setKey(key);
    }

    @Override
    public Create setOauthToken(java.lang.String oauthToken) {
      return (Create) super.setOauthToken(oauthToken);
    }

    @Override
    public Create setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Create) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Create setQuotaUser(java.lang.String quotaUser) {
      return (Create) super.setQuotaUser(quotaUser);
    }

    @Override
    public Create setUserIp(java.lang.String userIp) {
      return (Create) super.setUserIp(userIp);
    }

    @Override
    public Create set(String parameterName, Object value) {
      return (Create) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Users}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Users}. */
    @Override
    public Users build() {
      return new Users(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UsersRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUsersRequestInitializer(
        UsersRequestInitializer usersRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(usersRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
